### PR TITLE
Fixes Toolbar flicker and other toolbar issues

### LINKED ISSUE #304: Toolbar title is moving when swapping fragments
Hi!

I have one activity and two fragments. Each fragment has it's own `Toolbar` with different title. When I swap fragments (using `transaction.replace`) then the title is moving/jumping. In 2.1.0 it's a little better. Movement is a lot less visible but it's still there.
Here is a sample project that reproduces this issue: https://drive.google.com/open?id=0B4aF0Bxe-ecnRjBCaEdIMzMxYVU

It's not using any custom fonts, wrapping `Context` in `attachBaseContext` is enough to reproduce this issue.

### PR DESCRIPTION
**Pull request by chrisjenx**
Leads on from @ansman work.
Closes #386
Fixes #368 #327 #280
Probably Fixes #304 and #363

### CODE REVIEW

**Comment by chrisjenx** [comment]
Snapshot available: https://oss.sonatype.org/content/repositories/snapshots/uk/co/chrisjenx/calligraphy/2.3.0-SNAPSHOT/

File: calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java [hunk 1]
```diff
@@ -150,7 +150,29 @@ void onViewCreatedInternal(View view, final Context context, AttributeSet attrs)
         // Toolbar(Which underlies the ActionBar) for its children.
         if (CalligraphyUtils.canCheckForV7Toolbar() && view instanceof android.support.v7.widget.Toolbar) {
             final Toolbar toolbar = (Toolbar) view;
-            toolbar.getViewTreeObserver().addOnGlobalLayoutListener(new ToolbarLayoutListener(this, context, toolbar));
+            boolean hadTitle = toolbar.getTitle() != null;
```
Comment (hzsweers) [inline calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java]: Aren't these always `""`? At least for TextViews - setting null on them actually just sets to an empty string under the hood.

Comment (chrisjenx) [inline calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java]: I'm guessing you're saying it's safer to use `.isEmpty` on them?

Comment (hzsweers) [inline calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java]: right, I don't think the current code will ever equate to false currently

**Comment by chrisjenx** [comment]
Snapshot updated.

**Comment by hzsweers** [comment]
👍

File: calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java (hunk 1 above)
Comment (ansman) [inline calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java]: That's not true, the text is null when empty and set otherwise. Though it should probably be safe to use isEmpty.

Comment (hzsweers) [inline calligraphy/src/main/java/uk/co/chrisjenx/calligraphy/CalligraphyFactory.java]: Yeah we talked offline

**Comment by ansman** [comment]
I was wondering if we should perhaps have the code do this instead:
```java
CharSequence previousTitle = toolbar.getTitle();
CharSequence previousSubtitle = toolbar.getSubtitle();
toolbar.setTitle(" ");
toolbar.setSubtitle(" ");
// Iterate through the children
toolbar.setTitle(previousTitle);
toolbar.setSubtitle(previousSubtitle);
```

That way we can be sure it will set the title.

**Comment by chrisjenx** [comment]
@ansman yeah thats why I want some regression testing, I think as this is now done inline, we will avoid any race conditions compared to updating text between the layout listener like before. So I think it should be fine now.

**Comment by ansman** [comment]
Yeah, absolutely but say you set your title to an empty string to avoid getting NPEs, then calligraphy sets it back to null.

**Comment by chrisjenx** [comment]
Ahh good point. I'll update.

**Comment by chrisjenx** [comment]
Done, new snapshot.

**Comment by ansman** [comment]
I tried it, works beautifully. Both with titles/subtitles set in XML and in code.

**Comment by chrisjenx** [comment]
Had no know regressions, merging and releasing.
